name: hexo-deploy

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Build
        run: npm run build
     
      - name: Generate
        run: |
          hexo clean
          hexo generate
      
      - name: Deploy
        run: |
          git config --global user.name 'niliushall'
          git config --global user.email '1459775963@qq.com'
          # git clone https://github.com/GC-ZF/GC-ZF.github.io.git .deploy_git
          hexo deploy
